apiVersion: v1
kind: Secret
metadata:
  name: django-secrets
  namespace: default
type: Opaque
stringData:
  SECRET_KEY: "prod-secret-key-super-segura-sweet-witch"
  DATABASE_URL: "postgres://sweetuser:sweetpass@postgres-service:5432/sweetwitch_db"